sudo: required
services:
  - docker

before_install:
  - docker build -t fabee10/docker-react -f Dockerfile.dev .

script:
  - docker run fabe10/docker-react  npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstack-us-west-2-303456238923"
  bucket_ path: "docker-react"
  on:
    branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
